# Generated by Django 3.1 on 2020-08-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Country', models.CharField(max_length=60)),
                ('State', models.CharField(max_length=50)),
                ('University', models.CharField(max_length=100)),
                ('Previous_volunteering_experience', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=3)),
                ('Are_you_currently_volunteering_for_an_NGO', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Volunteers',
            },
        ),
    ]
