# Generated by Django 2.2.7 on 2019-12-03 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slaw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_votes', models.IntegerField(default=0)),
                ('nominees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slaw.Nominees')),
            ],
            options={
                'verbose_name_plural': 'votes',
            },
        ),
    ]
