# Generated by Django 2.2.7 on 2019-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaw', '0003_auto_20191204_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardcategories',
            name='Category_of_award',
            field=models.CharField(choices=[('Campus Life and Leadership Award', 'CLLA'), ('Most Outstanding Student Union Leader Award', 'MOSULA'), ('University Outstanding New Leader Award', 'UONLA'), ('Most Outstanding NGO Leadership Award', 'MONLA'), ('The Alumni Association Award', 'AAA'), ('Next Rated Award', 'NRA'), ('Unsung Hero Award', 'UHA'), ('Bridge Builder Award', 'BBA'), ('Vice Chancellor’s Volunteer Service Award', 'VCVSA'), ('Humanitarian Award', 'HA'), ('Award of Literary Excellence', 'ALE'), ('Student Media Personality Award', 'SMPA'), ('Entrepreneurial Merit Award', 'EMA')], max_length=10),
        ),
    ]
