# Generated by Django 2.2.7 on 2019-12-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaw', '0006_auto_20191204_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardcategories',
            name='award_details',
            field=models.TextField(default='Details about the award'),
        ),
    ]
