# Generated by Django 3.1.2 on 2020-10-10 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Award_Category', models.CharField(choices=[('CLLA', 'Campus Life and Leadership Award'), ('MOSULA', 'Most Outstanding Student Union Leader Award'), ('UONLA', 'University Outstanding New Leader Award'), ('MONLA', 'Most Outstanding NGO Leadership Award'), ('AAA', 'The Alumni Association Award'), ('NRA', 'Next Rated Award'), ('UHA', 'Unsung Hero Award'), ('BBA', 'Bridge Builder Award'), ('VCVSA', 'Vice Chancellor’s Volunteer Service Award'), ('HA', 'Humanitarian Award'), ('ALE', 'Award of Literary Excellence'), ('SMPA', 'Student Media Personality Award'), ('EMA', 'Entrepreneurial Merit Award')], max_length=10)),
                ('Details', models.TextField(default='Details about the award')),
            ],
            options={
                'verbose_name_plural': 'award Categories',
            },
        ),
        migrations.CreateModel(
            name='Nominees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Course_Of_Study', models.CharField(max_length=200)),
                ('Level', models.IntegerField(choices=[(100, 'First Year'), (200, 'Second Year'), (300, 'Third Year'), (400, 'Fourth Year'), (500, 'Fifth Year'), (600, 'Sixth Year'), (700, 'Seventh Year')], default='100L')),
                ('Institution', models.CharField(max_length=200)),
                ('Reason_for_nomination', models.TextField()),
                ('Cumulative_Grade_Point', models.FloatField(blank=True, max_length=4, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('Award_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slaw.awardcategories')),
            ],
            options={
                'verbose_name_plural': 'nominees',
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_votes', models.IntegerField(default=0)),
                ('nominees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='slaw.nominees')),
            ],
            options={
                'verbose_name_plural': 'votes',
            },
        ),
    ]
