# Generated by Django 3.1.2 on 2020-10-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
