# Generated by Django 3.1.2 on 2020-10-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaw', '0002_auto_20201010_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominees',
            old_name='Award_Category',
            new_name='award_category',
        ),
        migrations.RenameField(
            model_name='nominees',
            old_name='Course_Of_Study',
            new_name='course_of_study',
        ),
        migrations.RenameField(
            model_name='nominees',
            old_name='Cumulative_Grade_Point',
            new_name='cumulative_grade_point',
        ),
        migrations.RenameField(
            model_name='nominees',
            old_name='Full_Name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='nominees',
            old_name='Institution',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='nominees',
            old_name='Level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='nominees',
            old_name='Reason_for_nomination',
            new_name='reason_for_nomination',
        ),
    ]
